### PR TITLE
Final Capstone Project Front-End

### PR DESCRIPTION
**Pull request by ramiaquista**
### Student A:

**[Back-end](https://github.com/lfmnovaes/car-rental-back-end/pull/14):**
- Created Rails API with Postgres database integration
- Populated `seed.rb` with consistent data for cars, reservations, user, and cities
- Added methods to fetch all cars, reservations, cities, and users
- Added a way to fetch everything related to a reservation in one API call
- Added method to POST and DELETE cars (admin only)
- Added method to POST and DELETE reservations

**Front-end:**
- Created the React page to show all available cars in the company:
  - Created carousel styling with 3 cars at a time, similar to the design provided
  - Added animation to the carousel
  - Added name, brand, price information, and icons for each car
- Used Redux to fetch data from the [Rails Back-End](https://github.com/lfmnovaes/car-rental-back-end)

### Student B:

- Added reservations table with representative data
- Added reservedCar() to merge reservations and cars data.
- Added reservedCity() to merge reservations and cities data.
- Added isActive() to check the status of the reservation.
- Added a form to make a new reserve.
- Added axios pointing to the API endpoint to fetch all the reservations.
- Created the options from for cars and cities based on the redux store.
- Added delete btn on the reservations table fully functional
- Added cities, reservations reducers.
- Added log out btn to clear the current user session

### Student C:
- When the user clicks the "Add item" link in the navigation panel they can see a form for adding a new item. 
- When the user selects a specific item, they can see its full description (skip the "Rotate image" button) 
- If the user is admin and he clicks delete it will see a delete button showing up under each item in the main page.

### Back-End Pull Request Link: https://github.com/lfmnovaes/car-rental-back-end/pull/14

### CODE REVIEW

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
Hi @lfmnovaes, @elassis, @ramiaquista,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes

You can also consider:

- [x] I suggest adding some tests.
- [x] I know you are still finishing up the last touches, but I think some of your lines are very long and they are more difficult to read, so I suggest that you consider determining a maximum line length between yourselves.

## Highlights

- Very professional repository.
- Your code is clean.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by ramiaquista** [comment]
#### Thank @MuriloRoque for the amazing review! We have implemented new features, the requested changes and more styling to the app! 😄

**Comment by MuriloRoque** [comment]
Hi @ramiaquista, @lfmnovaes, @elassis,

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Review by MuriloRoque — APPROVED** [review]
Hi @ramiaquista, @lfmnovaes, @elassis,

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
